USE MANUFACTUREDB;

-- TOTAL MANUFACTURED QTY
SELECT SUM(`MANUFACTURED QTY`) AS TOTAL_MANUFACTURED_QTY FROM MANUFACTURES;
SELECT CONCAT(ROUND(SUM(`MANUFACTURED QTY`)/1000000, 2), " M") AS TOTAL_MANUFACTURED_QTY FROM MANUFACTURES;

-- TOTAL REJECTED QTY
SELECT SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM MANUFACTURES;
SELECT CONCAT(ROUND(SUM(`REJECTED QTY`)/1000, 2), " K") AS TOTAL_REJECTED_QTY FROM MANUFACTURES;

-- TOTAL PRODUCED QTY
SELECT SUM(`PRODUCED QTY`) AS TOTAL_PRODUCED_QTY FROM MANUFACTURES;
SELECT CONCAT(ROUND(SUM(`PRODUCED QTY`)/1000000, 2), " M") AS TOTAL_PRODUCED_QTY FROM MANUFACTURES;

-- TOTAL PROCESSED QTY
SELECT SUM(`PROCESSED QTY`) AS TOTAL_PROCESSED_QTY FROM MANUFACTURES;
SELECT CONCAT(ROUND(SUM(`PROCESSED QTY`)/1000000, 2), " M") AS TOTAL_PROCESSED_QTY FROM MANUFACTURES;

-- WASTAGE RATE
SELECT CONCAT(ROUND((SUM(`REJECTED QTY`)/ SUM(`MANUFACTURED QTY`)) * 100, 2), " %") AS WASTAGE_RATE FROM MANUFACTURES;

-- TOTAL EMPLOYEES
SELECT COUNT(DISTINCT `EMP CODE`) AS TOTAL_EMPLOYEES FROM MANUFACTURES;

-- TOTAL MACHINES
SELECT COUNT(DISTINCT `MACHINE CODE`) AS TOTAL_MACHINES FROM MANUFACTURES;

-- DEPARTMENT WISE MANUFACTURED VS REJECTED
SELECT `DEPARTMENT NAME`, 
CONCAT(ROUND(SUM(`MANUFACTURED QTY`)/1000000, 2), " M") AS MANUFACTURED_QTY,
CONCAT(ROUND(SUM(`REJECTED QTY`)/1000, 2), " K") AS REJECTED_QTY
FROM MANUFACTURES 
GROUP BY `DEPARTMENT NAME`;

-- EMPLOYEE WISE REJECTED QTY
SELECT `EMP NAME`, SUM(`REJECTED QTY`) AS REJECTED_QTY
FROM MANUFACTURES
GROUP BY `EMP NAME`
HAVING SUM(`REJECTED QTY`) > 0
ORDER BY SUM(`REJECTED QTY`) DESC;
# LIMIT 10;

-- MACHINE WISE REJECTED QTY
SELECT `MACHINE NAME`, SUM(`REJECTED QTY`) AS REJECTED_QTY
FROM MANUFACTURES 
GROUP BY `MACHINE NAME`
HAVING SUM(`REJECTED QTY`) > 0
ORDER BY SUM(`REJECTED QTY`) DESC;
# LIMIT 10;

-- MANUFACTURED QTY VS REJECTED QTY
SELECT `FISCAL DATE`, 
SUM(`MANUFACTURED QTY`) AS MANUFACTURED_QTY, 
SUM(`REJECTED QTY`) AS REJECTED_QTY
FROM MANUFACTURES 
GROUP BY `FISCAL DATE`
ORDER BY `FISCAL DATE`;

-- PRODUCTION COMPARISION TREND
SELECT `FISCAL DATE`,
SUM(`MANUFACTURED QTY`) AS MANUFACTURED_QTY,
SUM(`PRODUCED QTY`) AS PRODUCED_QTY,
SUM(`PROCESSED QTY`) AS PROCESSED_QTY,
SUM(`REJECTED QTY`) AS REJECTED_QTY
FROM MANUFACTURES
GROUP BY `FISCAL DATE`
ORDER BY `FISCAL DATE`;

SELECT COUNT(*) AS TOTAL FROM MANUFACTURES;







